# Generated by Django 4.1.2 on 2022-10-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='known_vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_id', models.IntegerField()),
                ('receipt_name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('cash_register', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('merchant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GettingWise.known_vendors')),
            ],
        ),
    ]
